@startuml
class Country {
    + name : string
    + activeUsers : int
}
class SystemInfoDataModel {
    + OnlineUserCount : int
    + Cpu : string
    + CpuSpeed : long
    + Ram : long
    + Countries : List<Country>
    # <<override>> OnInit() : void
}
ModelBase <|-- SystemInfoDataModel
@enduml
