@startuml
class AnalyticData {
    + country : string
    + activeUsers : int
}
class SystemData {
    + active_user : int
    + cpu : string
    + cpu_speed : long
    + ram : long
}
class SystemInfoController {
    - _systemMonitorView : SystemMonitorView
    + LoadSystemInfo() : void
    + <<override>> OnInit(view:List<ViewBase>) : void
    + OpenSystemMonitorView() : ViewBase
}
ControllerBase <|-- SystemInfoController
@enduml
