@startuml
class MessageController {
    - _messageView : MessageView
    + SendMessage() : void
    - AddMessage(userId:string, content:string, time:string, chatSessionId:string) : void
    + LoadMessage(chatSessionId:string, friendId:string) : void
    + ReadMessage(chatSessionId:string) : void
    + <<override>> OnInit(view:List<ViewBase>) : void
    + OpenMessageView(chatSessionId:string, friendId:string) : ViewBase
}
ControllerBase <|-- MessageController
@enduml
