@startuml
class WhiteboardController {
    - _render : LineRenderer
    + DrawAtPositionServerRpc(v:Vector3) : void
    + DrawAtPositionClientRpc(v:Vector3) : void
}
NetworkBehaviour <|-- WhiteboardController
@enduml
