@startuml
class HostRoomView {
    + ip : MobileInputField
    + port : MobileInputField
    + TMP_ip : TMP_InputField
    + TMP_port : TMP_InputField
    + createRoom : Button
    + host : Button
    + RoomDataModel : RoomDataModel
    + currentActiveRoom : string
    + hostingIcon : Sprite
    + selectIcon : Sprite
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
    + list : LoopScrollRect
    + RefreshList() : void
    + itemPrefab : GameObject
    - pool : Stack<Transform>
    + GetObject(index:int) : GameObject
    + ReturnObject(trans:Transform) : void
    + OnDeleteRoom : Action<string>
    + OnEditRoom : Action<string>
    + OnHostRoom : Action<RoomData>
    + ProvideData(trans:Transform, index:int) : void
}
ViewBase <|-- HostRoomView
LoopScrollPrefabSource <|-- HostRoomView
LoopScrollDataSource <|-- HostRoomView
@enduml
