@startuml
class JoinRoomView {
    + ip : TMP_InputField
    + port : TMP_InputField
    + join : Button
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- JoinRoomView
@enduml
