@startuml
class JoinRoomView {
    + ip : MobileInputField
    + port : MobileInputField
    + TMP_ip : TMP_InputField
    + TMP_port : TMP_InputField
    + join : Button
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- JoinRoomView
@enduml
