@startuml
class GeminiDataModel {
    + History : List<GeminiContent>
    + CurrentGeminiModelName : string
    + ChatBotAvatar : GameObject
    # <<override>> OnInit() : void
}
ModelBase <|-- GeminiDataModel
@enduml
