@startuml
class ChatBox {
    + role : TMP_Text
    + text : MarkdownRenderer
    + time : TMP_Text
    + background : Image
    + roundedCorners : ImageWithIndependentRoundedCorners
}
MonoBehaviour <|-- ChatBox
@enduml
