@startuml
class MessageView {
    + chatInput : MobileInputField
    + TMP_chatInput : TMP_InputField
    + send : Button
    + list : LoopScrollRect
    + ChatSession : ChatSession
    + friendId : string
    + back : Button
    + friendName : TMP_Text
    + inputRect : RectTransform
    + listRect : RectTransform
    + <<override>> Render(model:ModelBase) : void
    + RefreshList() : void
    - _listOffset : float
    - _inputOffset : float
    + <<override>> OnInit() : void
    + <<override>> MoveUpWhenOpenKeyboard(height:float) : void
    + itemPrefab : GameObject
    - pool : Stack<Transform>
    + GetObject(index:int) : GameObject
    + ReturnObject(trans:Transform) : void
    + ProvideData(trans:Transform, index:int) : void
}
ViewBase <|-- MessageView
LoopScrollPrefabSource <|-- MessageView
LoopScrollDataSource <|-- MessageView
@enduml
