@startuml
abstract class ControllerBase {
    + <<virtual>> Update() : void
    + <<virtual>> OnInit(views:List<ViewBase>) : void
    + GetArchitecture() : IArchitecture
}
IController <|-- ControllerBase
@enduml
