@startuml
abstract class ViewBase {
    + footer : Footer
    + header : Header
    + <<virtual>> MoveUpWhenOpenKeyboard(height:float) : void
    + {abstract} Render(model:ModelBase) : void
    + Display() : void
    + Hide() : void
    + {abstract} OnInit() : void
    # Awake() : void
}
MonoBehaviour <|-- ViewBase
@enduml
