@startuml
!include .\\.\Controller\BasicInput.puml
!include .\\.\Model\PlayerInputAction.puml
!include .\\.\Controller\Sensor\GyroscopeInput.puml
!include .\\.\Controller\Touch\OnScreenButton.puml
!include .\\.\Controller\Touch\OnScreenJoystick.puml
!include .\\.\Controller\Touch\OnScreenTouchBase.puml
!include .\\.\Controller\Touch\OnScreenTouchpad.puml
@enduml
