@startuml
class SignUpView {
    + email : MobileInputField
    + password : MobileInputField
    + re_password : MobileInputField
    + TMP_email : TMP_InputField
    + TMP_password : TMP_InputField
    + TMP_re_password : TMP_InputField
    + notice : TMP_Text
    + login : Button
    + signUp : Button
    + {static} EmailCheck(s:string) : bool
    + <<override>> Render(model:ModelBase) : void
    + SetNotice(notice:string) : void
    + SetNoticeSuccess(notice:string) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- SignUpView
@enduml
