@startuml
class UserProfileView {
    + userId : TMP_InputField
    + email : TMP_InputField
    + username : MobileInputField
    + description : MobileInputField
    + TMP_username : TMP_InputField
    + TMP_description : TMP_InputField
    + avatar : Image
    + dateOfBirth : DatePicker
    + save : Button
    + reset : Button
    + resetPassword : Button
    + signOut : Button
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- UserProfileView
@enduml
