@startuml
class FriendDataModel {
    + FriendList : Dictionary<string, FriendData>
    + RequestList : Dictionary<string, FriendData>
    # <<override>> OnInit() : void
}
ModelBase <|-- FriendDataModel
@enduml
