@startuml
class UserProfileDataModel {
    + UserProfileData : UserAccountData
    + FetchProfile(auth:FirebaseAuth, onSuccess:Action, onFailure:Action) : void
    # <<override>> OnInit() : void
}
ModelBase <|-- UserProfileDataModel
@enduml
