@startuml
class UserAccountData {
    + Avatar : Texture2D
    + Description : string
    + Username : string
    + DateOfBirth : DateTime
    + Email : string
    + UserId : string = ""
    + IsAdmin : bool = false
}
@enduml
