@startuml
class ObjectPuttingArea {
    + ignore : LayerMask
    - _originMousePos : Vector3
    - _originPos : Vector3
    - _originRot : float
    + rotSelected : ItemObject
    + moveSelected : ItemObject
    + OnModified : Action<ItemObject>
    + isRotate : bool
    + Awake() : void
    + SetRotate(rotate:bool) : void
    + OnBeginDrag(eventData:PointerEventData) : void
    + RestoreMove() : void
    + RestoreRot() : void
    + OnDrag(eventData:PointerEventData) : void
    + OnEndDrag(eventData:PointerEventData) : void
    + GetArchitecture() : IArchitecture
}
MonoBehaviour <|-- ObjectPuttingArea
IBeginDragHandler <|-- ObjectPuttingArea
IDragHandler <|-- ObjectPuttingArea
IEndDragHandler <|-- ObjectPuttingArea
IController <|-- ObjectPuttingArea
@enduml
