@startuml
!include .\\.\Controller\EEmotion.puml
!include .\\.\Controller\ExpressionControl.puml
!include .\\.\Controller\GeminiController.puml
!include .\\.\Model\GeminiDataModel.puml
!include .\\.\View\ChatBotView.puml
@enduml
