@startuml
class FriendManagementController {
    - _friendListView : FriendListView
    + <<override>> OnInit(view:List<ViewBase>) : void
    + LoadFriendList() : void
    + SendFriendRequest(targetUserId:string) : void
    + AcceptFriendRequest(requesterId:string) : void
    + RefuseFriendRequest(requesterId:string) : void
    + RemoveFriend(friendId:string) : void
    + OpenFriendListView() : ViewBase
}
ControllerBase <|-- FriendManagementController
@enduml
