@startuml
class ModelListView {
    + modelListScrollViewParent : RectTransform
    + listItemTemplate : GameObject
    + items : List<ModelListItem>
    + selectAsChatBotAvatar : Button
    + selectAsCharacterInRoom : Button
    + previewModelPoint : Transform
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- ModelListView
@enduml
