@startuml
!include .\\.\RoomMessageController.puml
!include .\\.\RoomMessageDataModel.puml
!include .\\.\RoomMessageView.puml
RoomMessageController o-- RoomMessageDataModel
RoomMessageController o-- RoomMessageView
@enduml
