@startuml
class UserAuthController {
    - _loginView : LoginView
    - _signUpView : SignUpView
    - _userProfileView : UserProfileView
    + OpenSignUpView() : ViewBase
    + OpenLoginView() : ViewBase
    - ConvertException(exception:string) : string
    - TransitionToLoginViewAfterDelay() : IEnumerator
    + SignUp() : void
    + ResetPassword() : void
    + SendTokenDeltaTime : float = 0
    + <<readonly>> SendTokenTimeout : float = 3
    + <<override>> Update() : void
    + Login() : void
    + SignOut() : void
    + <<override>> OnInit(view:List<ViewBase>) : void
}
ControllerBase <|-- UserAuthController
@enduml
