@startuml
class UserAuthController {
    - _loginView : LoginView
    - _signUpView : SignUpView
    - _userProfileView : UserProfileView
    + OpenSignUpView() : ViewBase
    + OpenLoginView() : ViewBase
    + SignUp() : void
    + ResetPassword() : void
    + Login() : void
    + SignOut() : void
    + <<override>> OnInit(view:List<ViewBase>) : void
}
ControllerBase <|-- UserAuthController
@enduml
