@startuml
class UserProfileController {
    - _userProfileView : UserProfileView
    + OpenUserProfileView() : ViewBase
    + SaveUserProfile() : void
    + <<override>> OnInit(view:List<ViewBase>) : void
}
ControllerBase <|-- UserProfileController
@enduml
