@startuml
class EnvironmentObjectManager {
    - _environmentEditView : EnvironmentEditView
    + SaveRoomEnvironmentData() : void
    + LoadRoomEnvironmentData(roomId:string, onSuccess:Action) : void
    + OpenEnvironmentEditView(roomId:string) : ViewBase
    + <<override>> OnInit(view:List<ViewBase>) : void
}
ControllerBase <|-- EnvironmentObjectManager
@enduml
