@startuml
class RoomDataModel {
    + RoomsData : List<RoomData>
    + CurrentHostRoomData : RoomData
    + CurrentHostRoomJoinedUser : List<UserAccountData>
    # <<override>> OnInit() : void
}
ModelBase <|-- RoomDataModel
@enduml
