@startuml
class FirebaseRealTimeDatabaseModel {
    + DatabaseRootReference : DatabaseReference
    + <<override>> InitFirebase() : void
}
FirebaseModelBase <|-- FirebaseRealTimeDatabaseModel
@enduml
