@startuml
class EmotionList {
    + neutral : Button
    + relax : Button
    + angry : Button
    + surprised : Button
    + sad : Button
    + fun : Button
    + Awake() : void
    + GetArchitecture() : IArchitecture
}
MonoBehaviour <|-- EmotionList
IController <|-- EmotionList
@enduml
