@startuml
class PlayerExpressionController {
    - _playerController : PlayerController
    + Start() : void
    + InputRegister() : void
    + SetExpressionServerRpc(v:int) : void
    + SetExpressionClientRpc(v:int) : void
    + Relax() : void
    + Angry() : void
    + Surprised() : void
    + Sad() : void
    + Fun() : void
    + Neutral() : void
    + GetArchitecture() : IArchitecture
}
NetworkBehaviour <|-- PlayerExpressionController
IController <|-- PlayerExpressionController
@enduml
