@startuml
class PlayerExpressionController {
    + vrm10Instance : Vrm10Instance
    + SetExpressionServerRpc(v:int) : void
    + SetExpressionClientRpc(v:int) : void
    + Relax() : void
    + Angry() : void
    + Surprised() : void
    + Sad() : void
    + Fun() : void
    + Neutral() : void
}
NetworkBehaviour <|-- PlayerExpressionController
@enduml
