@startuml
class CharacterModelDataModel {
    + ModelId : List<string>
    + ChatRoomSelectModelId : string
    + ChatBotSelectModelId : string
    + LoadModelList() : void
    + LoadModelFromInternal(fileName:string) : byte[]
    + CreateCharacter(modelId:string, onVrmModelLoaded:Action<GameObject>) : void
    # <<override>> OnInit() : void
}
ModelBase <|-- CharacterModelDataModel
@enduml
