@startuml
!include .\\.\Controller\EnvironmentObjectManager.puml
!include .\\.\Model\EnvironmentDataModel.puml
!include .\\.\Model\EnvironmentItemData.puml
!include .\\.\View\EnvironmentEditView.puml
!include .\\.\View\ItemObject.puml
!include .\\.\View\ObjectListItem.puml
!include .\\.\View\ObjectPuttingArea.puml
EnvironmentObjectManager o-- EnvironmentEditView
EnvironmentObjectManager o-- EnvironmentDataModel
EnvironmentDataModel *-- EnvironmentItemData
EnvironmentEditView *-- ObjectListItem
@enduml
