@startuml
class GeminiController {
    - _chatBotView : ChatBotView
    - <<async>> OnChat(text:string) : void
    - ExpressionControl(chatContent:string) : string
    + NewChat() : void
    + <<override>> OnInit(view:List<ViewBase>) : void
    + AddMessage(role:string, text:string) : void
    + OpenChatBotView() : ViewBase
}
ControllerBase <|-- GeminiController
@enduml
