@startuml
class UserListView {
    + scrollViewParent : RectTransform
    + listItemTemplate : GameObject
    + items : List<FriendListItem>
    + userIdSearch : TMP_InputField
    + <<override>> Render(model:ModelBase) : void
    + <<override>> OnInit() : void
}
ViewBase <|-- UserListView
@enduml
