@startuml
class UserListItem {
    + userId : TMP_Text
    + username : TMP_Text
    + description : TMP_Text
    + avatar : Image
    + dateOfBirth : TMP_Text
    + button1 : Button
    + button2 : Button
    + button1Icon : Image
}
MonoBehaviour <|-- UserListItem
@enduml
