@startuml
!include .\\.\Controller\ConnectionManager.puml
!include .\\.\Controller\RoomManager.puml
!include .\\.\Model\RoomData.puml
!include .\\.\Model\RoomDataModel.puml
!include .\\.\View\HostRoomView.puml
!include .\\.\View\JoinedUserListItem.puml
!include .\\.\View\JoinedUserListView.puml
!include .\\.\View\JoinRoomView.puml
!include .\\.\View\RoomListItem.puml
ConnectionManager o-- JoinRoomView
ConnectionManager o-- HostRoomView
RoomManager o-- RoomDataModel
RoomManager o-- JoinRoomView
RoomManager o-- HostRoomView
RoomDataModel *-- RoomData
HostRoomView *-- RoomListItem
ConnectionManager o-- JoinedUserListView
JoinedUserListView *-- JoinedUserListItem
@enduml
